# Generated by Django 3.1.6 on 2021-02-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('currencu', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('TRY', 'も'), ('INR', '₹')], default='USD', max_length=3)),
            ],
        ),
    ]
