# Generated by Django 3.1.6 on 2021-02-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('tax', models.FloatField(default=0, verbose_name='Tax')),
                ('tax_included', models.BooleanField(default=True, verbose_name='Tax included')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified')),
                ('order', models.IntegerField(default=255, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shops.shop')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField(default=0, verbose_name='Sales Price')),
                ('visible_web', models.BooleanField(default=True, verbose_name='Visible for web')),
                ('archive', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
        ),
    ]
