# Generated by Django 3.1.6 on 2021-02-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop',
        ),
    ]
